[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "kanji_nn"
version = "0.1.0"
description = "Experiments with neural networks for Kanji recognition"
requires-python = ">=3.12"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
kanji_nn = ["io/*.tsv"]

[tool.pytest.ini_options]
addopts = "-v"
